package com.company;

public class Main {
    /**COORDINATES ARE REVERSED
     * LOOK UP HOW TO DISABLE BUTTON CLICKING EFFECTS AND USE IT IN THE AUDIO BUTTON.
     * MAYBE BECAUSE OF THE SINGLETON, THE MINES ARE BEING PLACED AT THE SAME PLACE EACH TIME.
     * FIX THE RANDOM THING.
     * FIND OUT A WAY TO ALWAYS MAKE THE FIRST REVEAL TO BE AN EMPTY CELL.
     * HOW TO FIT THE FRAME THE SIZE OF THE SCREEN.
     * FOR NOW I AM KEEPING THE BUTTON ENABLED WITH NUMBERS ICONS ON IT WHEN CLICKED. IF YOU EVER FIND OUT HOW TO SET AN ICON ON A DISABLED BUTTON REMEMBER TO USE IT.
     * BUG OCCURRING WHEN PLACING A FLAG ON AN EMPTY CELL THEN REVEALING WHAT IS AROUND IT; IT WON'T BE REVEALED ANYMORE!
     */
    public static void main(String[] args) throws InterruptedException {
        //new MineSweeper(5, 11);         // Console.
        new MineSweeperGUI();          //GUI.
    }
}